services:
  - type: web
    name: milk-records
    plan: free
    region: oregon

    # Render에서 Dockerfile을 기준으로만 실행되도록 설정
    dockerfilePath: "Dockerfile"

    envVars:
      - key: NODE_ENV
        value: "production"

